name: Metrics

# 必须有 on，顶格写，下面至少保留一个触发器
on:
  workflow_dispatch:        # 网页端手动触发
  schedule:
    - cron: "0 18 * * *"    # 每天 UTC 18:00 运行（北京+8 为次日 02:00）

# 给 Actions 写文件的权限（否则可能失败）
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}   # 默认令牌足够
          filename: metrics.svg                # 生成在仓库根目录
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Shanghai
